<html>

<head>
    <title>This is a test page</title>
</head>

<body>
    <div id="content">              
        $components/textComponent(id="welcomeMessage", text="<strong>Some default text</strong>", editable="false")$
        $components/textComponent(id="aboutMe", text="default about me text")$
        $components/imageComponent()$
    </div>

    <div id="footer">
        $components/footerComponent()$
    </div>

</body>
</html>