drop user @DB_ADMIN_USER_PASSWORD@ cascade;

create user @DB_ADMIN_USER_PASSWORD@ identified by @DB_ADMIN_USER_PASSWORD@ 
    default tablespace users
    PROFILE DEFAULT
    ACCOUNT UNLOCK;

GRANT RESOURCE TO @DB_ADMIN_USER_PASSWORD@ WITH ADMIN OPTION;
GRANT CONNECT TO @DB_ADMIN_USER_PASSWORD@ WITH ADMIN OPTION;

ALTER USER @DB_ADMIN_USER_PASSWORD@ DEFAULT ROLE ALL;

GRANT CREATE SESSION TO @DB_ADMIN_USER_PASSWORD@;
GRANT ALTER SESSION TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE USER TO @DB_ADMIN_USER_PASSWORD@;
GRANT ALTER USER TO @DB_ADMIN_USER_PASSWORD@;
GRANT DROP USER TO @DB_ADMIN_USER_PASSWORD@;
GRANT ALTER SYSTEM TO @DB_ADMIN_USER_PASSWORD@;
GRANT SELECT ANY DICTIONARY TO @DB_ADMIN_USER_PASSWORD@;
GRANT UNLIMITED TABLESPACE TO @DB_ADMIN_USER_PASSWORD@ WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE CLUSTER TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE SYNONYM TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE VIEW TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE DATABASE LINK TO @DB_ADMIN_USER_PASSWORD@;
GRANT CREATE TABLE TO @DB_ADMIN_USER_PASSWORD@;
GRANT GRANT ANY PRIVILEGE TO @DB_ADMIN_USER_PASSWORD@;
GRANT SELECT ANY TABLE TO @DB_ADMIN_USER_PASSWORD@;

-- All create privs

grant Create Any Index  to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Materialized View  to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Procedure  to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Sequence to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Synonym  to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Table  to @DB_ADMIN_USER_PASSWORD@;
grant Create Any Trigger to @DB_ADMIN_USER_PASSWORD@;
grant Create Any view  to @DB_ADMIN_USER_PASSWORD@;

-- All drop privs

grant Drop Any Index to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Materialized View to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Procedure to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Sequence to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Synonym to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Table to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any Trigger to @DB_ADMIN_USER_PASSWORD@;
grant Drop Any View to @DB_ADMIN_USER_PASSWORD@;

-- All alter privs

grant Alter Any Index to @DB_ADMIN_USER_PASSWORD@;
grant Alter Any Materialized View to @DB_ADMIN_USER_PASSWORD@;
grant Alter Any Table to @DB_ADMIN_USER_PASSWORD@;
grant Alter Any Trigger to @DB_ADMIN_USER_PASSWORD@;

-- All dml privs

grant SELECT any table to @DB_ADMIN_USER_PASSWORD@;
grant INSERT any table to @DB_ADMIN_USER_PASSWORD@;
grant UPDATE any table to @DB_ADMIN_USER_PASSWORD@;
grant DELETE any TABLE to @DB_ADMIN_USER_PASSWORD@;