DROP USER @APP_USER_NAME@ CASCADE
/

CREATE USER @APP_USER_NAME@ IDENTIFIED BY @APP_USER_PASSWORD@ DEFAULT TABLESPACE @TABLESPACE_NAME@
/

ALTER USER @APP_USER_NAME@ ACCOUNT UNLOCK
/

GRANT CREATE SESSION TO @APP_USER_NAME@
/
GRANT RESOURCE TO @APP_USER_NAME@
/
GRANT CREATE VIEW TO @APP_USER_NAME@
/
GRANT CREATE MATERIALIZED VIEW TO @APP_USER_NAME@
/
GRANT CREATE TABLE TO @APP_USER_NAME@
/
GRANT CREATE SYNONYM TO @APP_USER_NAME@
/
GRANT CREATE JOB TO @APP_USER_NAME@
/
